local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug("sheerun/vim-polyglot")
Plug("nvim-lualine/lualine.nvim")
Plug("kyazdani42/nvim-web-devicons")
Plug("navarasu/onedark.nvim")
Plug("alvan/vim-closetag")
Plug("Yggdroot/indentLine")
Plug("jiangmiao/auto-pairs")
Plug("mhinz/vim-signify")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim")
Plug("nvim-telescope/telescope-fzf-native.nvim", { ["do"] = "make" })
Plug("pangloss/vim-javascript")
Plug("leafgarland/typescript-vim")
Plug("peitalin/vim-jsx-typescript")
Plug("styled-components/vim-styled-components", { ["branch"] = "main" })
Plug("neoclide/coc.nvim", { ["branch"] = "release" })
Plug("matze/vim-move")
Plug("tpope/vim-surround")
Plug("preservim/nerdcommenter")
vim.call('plug#end')

